algoritmo "valoresPares"
// Algoritmo que retorna uma contagem até um número dado pelo usuário.
var
   fim, cont:Inteiro
inicio
      Escreval("---------------------")
      Escreval(" CONTADOR CRESCENTE: ")
      Escreval("---------------------")
      Escreval("")
      
      Escreva("Gostaria de contar até que número? ")
      Leia(fim)
      Para cont <- 0 ate fim passo 2 faca
           Escreva(cont)
      FimPara
      Escreval("")
      Escreval("Terminei de contar.")
fimalgoritmo
