algoritmo "soma"
// Algoritmo que pede dois números ao usuário e retorna a soma entre eles.
var
   N1, N2, S: Inteiro
inicio
      Escreval("----------------")
      Escreval(" SOMAR VALORES: ")
      Escreval("----------------")
      Escreval("")
      Escreva("Digite o primeiro número: ")
      Leia(N1)
      Escreva("Digite o segundo número: ")
      Leia(N2)
      S <- N1 + N2
      Escreval("A soma entre", N1, " e", N2, " é igual a", S, ".")
fimalgoritmo
