algoritmo "contarAte10"
// Algoritmo que conta de 1 até 10 utilizando a estrutura de repetição REPITA.
var
   contador: Inteiro
inicio
      Escreval("---------------------")
      Escreval(" CONTAR DE 1 ATÉ 10: ")
      Escreval("---------------------")
      Escreval("")
      
      Escreval("Contando de 1 até 10:")
      Para contador <- 1 ate 10 passo 1 faca
           Escreva(contador, "...")
      FimPara
      Escreval("")
fimalgoritmo
