algoritmo "contarDe10Ate0"
// Algoritmo que conta de 10 até 0 utilizando a estrutura de repetição ENQUANTO.
var
   contador: Inteiro
inicio
      Escreval("-----------")
      Escreval(" CONTADOR: ")
      Escreval("-----------")
      Escreval("")
      
      contador <- 10
      Escreval("Contando de 10 até 0:")
      Enquanto (contador >= 0) faca
               Escreval("Contador: ", contador)
               contador <- contador - 1
      FimEnquanto
fimalgoritmo
