algoritmo "conteAte10"
// Algoritmo que retorna a contagem de 1 a 10 utilizando a estrutura de repetição
// ENQUANTO.
var
   contador: Inteiro
inicio
      Escreval("----------")
      Escreval(" CONTADOR ")
      Escreval("----------")
      Escreval("")
      
      contador <- 0
      Escreval("Contando até 10:")
      Enquanto (contador <= 10) faca
               Escreval("Contador: ", contador)
               contador <- contador + 1
      FimEnquanto
fimalgoritmo
